### ISSUE TITLE
Unable to run with SublimeText 4 and Package Control 4

### ISSUE THREAD

**Issue by meengit** [daveleroy/SublimeDebugger#242]
Hi @daveleroy 

Thank you very much for this package. I used it for quite some time. However, with Package Control Release 4.0.1 I'm unable to run it anymore. I'm not sure if it is a local issue. However, the following installation methods results in Python errors in SublimeText's console, and I can't find a way to make it work again.

### General

- SublimeText Build 4168
- Package Control Version 4.0.1
- Platform Apple MacOS 14.1.2

### Preparation

Cleared `/Users/***/Library/Caches/Sublime Text/Cache` before installation.

### Method 1 – Use the package from Package Control

- `cmd` + `shift` + `p` > _Package Control: Install Package_ > _Debugger_ `Enter`
- Package Control installs the package
- Debugger's release notes (messages) showing up in a new tab
- Menu _View_ > _Show Console_

The console shows the following error:

```text
Unable to parse color value var(background) at Packages/Debugger/contributes/ColorScheme/Mariana.sublime-color-scheme:5:18
reloading plugin Debugger.start
Debugger: Installing Debugger33
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 432, in load_module
    m.plugin_loaded()
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/start.py", line 56, in plugin_loaded
    data = sublime.load_resource("Packages/Debugger/modules/adapters/util/bridge33.py")
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime.py", line 1199, in load_resource
    raise FileNotFoundError(f'resource "{name}" not found')
FileNotFoundError: resource "Packages/Debugger/modules/adapters/util/bridge33.py" not found
top level value must be an array
top level value must be an array
reloading python 3.3 plugin Debugger33.bridge33
generating syntax summary
```

When I try to open the debugger from Menu _Tools_ > _Debugger_ > _Open_ the console shows:

```text
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1502, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/command.py", line 105, in is_visible
    return command.is_visible(self.window)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/command.py", line 76, in is_visible
    if self.flags & Command.development and not Settings.development:
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/settings.py", line 17, in __get__
    return SettingsRegistery.settings.get(self.key, self.default)
AttributeError: type object 'SettingsRegistery' has no attribute 'settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1478, in is_enabled_
    ret = self.is_enabled(**args)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/command.py", line 100, in is_enabled
    command = CommandsRegistry.commands_by_action[action]
KeyError: 'lldb_display'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1502, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/command.py", line 104, in is_visible
    command = CommandsRegistry.commands_by_action[action]
KeyError: 'lldb_display'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1478, in is_enabled_
    ret = self.is_enabled(**args)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/command.py", line 100, in is_enabled
    command = CommandsRegistry.commands_by_action[action]
KeyError: 'lldb_toggle_dereference'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1502, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/command.py", line 104, in is_visible
    command = CommandsRegistry.commands_by_action[action]
KeyError: 'lldb_toggle_dereference'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1658, in run_
    return self.run(**args)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/command.py", line 97, in run
    command.run(self.window, kwargs)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/command.py", line 63, in run
    debugger = Debugger.create(window, skip_project_check = bool(self.flags & Command.allow_debugger_outside_project))
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/debugger.py", line 39, in create
    debugger = Debugger.get(window, create=True, skip_project_check=skip_project_check)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/debugger.py", line 62, in get
    instance = Debugger(window, skip_project_check=skip_project_check)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/debugger.py", line 97, in __init__
    self.project = Project(window, skip_project_check)
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/project.py", line 16, in __init__
    if not skip_project_check and not Settings.global_debugger_configurations:
  File "/Users/***/Library/Application Support/Sublime Text/Packages/Debugger/modules/settings.py", line 17, in __get__
    return SettingsRegistery.settings.get(self.key, self.default)
AttributeError: type object 'SettingsRegistery' has no attribute 'settings'
```

### Method 2 – Install from GitHub Repository using [Package Control's _Add Repository_](https://packagecontrol.io/docs/usage) command(s)

- `cmd` + `shift` + `p` > _Package Control: Add Repository_ `Enter`
- Add `https://github.com/daveleroy/SublimeDebugger/` `Enter`
- `cmd` + `shift` + `p` > _Package Control: Install Package_ > _**SublimeDebugger**_ `Enter`
- Package Control installs the package
- Debugger's release notes (messages) showing up in a new tab
- Menu _View_ > _Show Console_

The console shows the following error:

```text
reloading plugin SublimeDebugger.start
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/***/Library/Application Support/Sublime Text/Packages/SublimeDebugger/start.py", line 22, in <module>
    from .modules.adapters.util.bridge import DebuggerBridgeCommand
  File "/Users/***/Library/Application Support/Sublime Text/Packages/SublimeDebugger/modules/adapters/__init__.py", line 1, in <module>
    from .lldb import LLDB
  File "/Users/***/Library/Application Support/Sublime Text/Packages/SublimeDebugger/modules/adapters/lldb.py", line 11, in <module>
    from .import util
  File "/Users/***/Library/Application Support/Sublime Text/Packages/SublimeDebugger/modules/adapters/util/__init__.py", line 10, in <module>
    from .import process
ImportError: cannot import name 'process' from partially initialized module 'SublimeDebugger.modules.adapters.util' (most likely due to a circular import) (/Users/***/Library/Application Support/Sublime Text/Packages/SublimeDebugger/modules/adapters/util/__init__.py)
top level value must be an array
top level value must be an array
generating syntax summary
```

Also, `cmd` + `shift` + `p` > _Package Control: Satisfy Libraries_ results in:

```text
Package Control: The library "psutil" is not available for Python 3.8
error: Package Control

One or more libraries could not be installed or updated.

Please check the console for details.
```

### Summary

- I can't install Debugger anymore.
- I can't find the reason for it. Perhaps, it has to do with on how Package Control 4.X loads the dependencies.

### Question

Do you see a reason for behavior? Do I have missed something? Can you reproduce the errors?

**Comment by daveleroy** [comment]
I don't know why installing via package control would not be working. 

https://github.com/daveleroy/SublimeDebugger/commit/c124fb018163492216636112ad5f95aec92dbd86 should fix your issue with installing from the main branch

**Comment by meengit** [comment]
Hi @daveleroy, thank you very much for your prompt answer. I can confirm that the Debugger is working again with both installation methods.
