### ISSUE TITLE
Python debugger wont start

### ISSUE THREAD

**Issue by DJManas** [daveleroy/SublimeDebugger#250]
Hello,

after some time I had returned to my Django project. Packages had updated and I am unable to start debugger. I was curious, but I get this error on console.

```
Traceback (most recent call last):
  File "/home/djmanas/.config/sublime-text/Packages/Debugger/modules/core/asyncio.py", line 139, in call_exception_handler
    raise context['exception']
  File "/home/djmanas/.config/sublime-text/Packages/Debugger/modules/debugger.py", line 299, in launch
    await self.launch(self.breakpoints, adapter_configuration, configuration_expanded, no_debug=no_debug)
  File "/home/djmanas/.config/sublime-text/Packages/Debugger/modules/debugger.py", line 332, in launch
    session.on_updated_networking_requests = self.on_session_networking_requests_updated
AttributeError: 'Debugger' object has no attribute 'on_session_networking_requests_updated'

Traceback (most recent call last):
  File "/home/djmanas/.config/sublime-text/Packages/Debugger/modules/core/asyncio.py", line 139, in call_exception_handler
    raise context['exception']
  File "/home/djmanas/.config/sublime-text/Packages/Debugger/modules/debugger.py", line 299, in launch
    await self.launch(self.breakpoints, adapter_configuration, configuration_expanded, no_debug=no_debug)
  File "/home/djmanas/.config/sublime-text/Packages/Debugger/modules/debugger.py", line 332, in launch
    session.on_updated_networking_requests = self.on_session_networking_requests_updated
AttributeError: 'Debugger' object has no attribute 'on_session_networking_requests_updated'
```
It seems to have been added in commit [d397852](https://github.com/daveleroy/SublimeDebugger/commit/d397852d1a85b14d6e1b3dd9f3726bb788e6df0e), but I still am not able to debug it to find what is missing. :-(

Gentoo linux: **Linux RinceWind 6.7.7-Air SMP PREEMPT_DYNAMIC Sun Mar  3 00:06:03 CET 2024 x86_64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz GenuineIntel GNU/Linux**
Sublime: **[ebuild   R    ] app-editors/sublime-text-4_p4169::gentoo  USE="dbus"**

Thanks,
Regards,
Petr Sourek

**Comment by DJManas** [comment]
I had commented out line [332](https://github.com/daveleroy/SublimeDebugger/blob/a7ef0da4a7c80e7371b9a78f1724b284ff5b1c35/modules/debugger.py#L332) in modules/debugger.py and it seems to be working, but not sure if its the correct repair.

**Comment by daveleroy** [comment]
Should be fixed here https://github.com/daveleroy/SublimeDebugger/commit/89e84ed6c45513420a58fb22a3dbf9fb5355c7fe

**Comment by DJManas** [comment]
Used git pull, tested and its working, thank you!
