### ISSUE TITLE
Debbugger not starting

### ISSUE THREAD

**Issue by d0sse** [daveleroy/SublimeDebugger#255]
Output:
`Traceback (most recent call last):
  File "/Users/d0sse/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/debugger.py", line 69, in get
    instance = Debugger(window, skip_project_check=skip_project_check)
  File "/Users/d0sse/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/debugger.py", line 118, in __init__
    self.console: ConsoleOutputPanel = ConsoleOutputPanel(self)
  File "/Users/d0sse/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/console.py", line 22, in __init__
    super().__init__(debugger, 'Debugger Console', name='Console', show_tabs=True, remove_last_newline=True)
  File "/Users/d0sse/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/output_panel.py", line 137, in __init__
    scaled_font = settings.get('font_size') * (Settings.minimum_console_height + 1.75) / 5
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'`

**Comment by d0sse** [comment]
Now works!

**Comment by daveleroy** [comment]
> Now works!

Did you have to do anything to fix this? Restart Sublime or something?

**Comment by yowkah** [comment]
I ran into the same issue.
Fixed it by setting my "font_size" to the default in my user settings, then restarting sublime.

**Comment by d0sse** [comment]
> > Now works!
> 
> Did you have to do anything to fix this? Restart Sublime or something?

I changed Font_size, then I restarted Sublime!
