### ISSUE TITLE
Node.js debugging: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by 8Observer8** [daveleroy/SublimeDebugger#286]
I try to make the same steps for Node.js like for Python:

![image](https://github.com/user-attachments/assets/c32d55af-fd81-4600-ae95-7e91642b3168)

```
Traceback (most recent call last):
  File "E:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1218, in preview_
    ret = self.preview(v)
  File "C:\Users\8Observer8\AppData\Roaming\Sublime Text\Packages\Debugger\modules\ui\input.py", line 145, in preview
    if preview := self.values[arg].preview:
TypeError: list indices must be integers or slices, not str
```

**Comment by daveleroy** [comment]
You can add your own configuration see https://code.visualstudio.com/docs/nodejs/nodejs-debugging

**Comment by 8Observer8** [comment]
@daveleroy, please, help me. I try to use this configuration: [Launch configuration support for 'npm' and other tools](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools)

What should I try to change here?

```
{
	"folders":
	[
		{
			"path": ".",
		}
	],
	"debugger_configurations":
	[
		{
		  "name": "Launch via npm",
		  "type": "node",
		  "request": "launch",
		  "cwd": "${workspaceFolder}",
		  "runtimeExecutable": "npm",
		  "runtimeArgs": ["run-script", "debug"]
		}
	],
}
```
Output:
```
"C:\Program Files\nodejs\npm.cmd" run-script debug
Could not read source map for file:///C:/Program%20Files/nodejs/node_modules/npm/node_modules/walk-up-path/dist/cjs/index.js: ENOENT: no such file or directory, open 'c:\Program Files\nodejs\node_modules\npm\node_modules\walk-up-path\dist\cjs\index.js.map'
Could not read source map for file:///C:/Program%20Files/nodejs/node_modules/npm/node_modules/which/node_modules/isexe/dist/cjs/index.js: ENOENT: no such file or directory, open 'c:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\dist\cjs\index.js.map'
Could not read source map for file:///C:/Program%20Files/nodejs/node_modules/npm/node_modules/which/node_modules/isexe/dist/cjs/posix.js: ENOENT: no such file or directory, open 'c:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\dist\cjs\posix.js.map'
Could not read source map for file:///C:/Program%20Files/nodejs/node_modules/npm/node_modules/which/node_modules/isexe/dist/cjs/win32.js: ENOENT: no such file or directory, open 'c:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\dist\cjs\win32.js.map'
Could not read source map for file:///C:/Program%20Files/nodejs/node_modules/npm/node_modules/which/node_modules/isexe/dist/cjs/options.js: ENOENT: no such file or directory, open 'c:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\dist\cjs\options.js.map'
Could not read source map for file:///C:/Program%20Files/nodejs/node_modules/npm/node_modules/minipass/dist/commonjs/index.js: ENOENT: no such file or directory, open 'c:\Program Files\nodejs\node_modules\npm\node_modules\minipass\dist\commonjs\index.js.map'
Process exited with code 1
Debugging ended
```
![image](https://github.com/user-attachments/assets/596fc5b4-af3a-4467-8093-0880cc3dc3cf)

**Comment by 8Observer8** [comment]
This configuration works: [Multi version support](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_multi-version-support)

```
{
	"folders":
	[
		{
			"path": ".",
		}
	],
	"debugger_configurations":
	[
		{
		  "type": "node",
		  "request": "launch",
		  "name": "Launch test",
		  "runtimeVersion": "14",
		  "program": "${workspaceFolder}/index.js"
		}
	],
}
```
Start debugging:
![image](https://github.com/user-attachments/assets/037f072f-8d6a-40fb-b907-226befcaf7c2)
Finish debugging:
![image](https://github.com/user-attachments/assets/2f4516c0-cc81-4b03-95ef-8bfa9cd6d808)

**Comment by 8Observer8** [comment]
@daveleroy, could you add the same way to add a configuration file like for the C language:

![image](https://github.com/user-attachments/assets/06f9e7e8-8d2c-4a61-9189-2893784e5c07)

to add the default configuration file like this:

```
{
	"folders":
	[
		{
			"path": ".",
		}
	],
	"debugger_configurations":
	[
		{
		  "type": "node",
		  "request": "launch",
		  "name": "Launch test",
		  "runtimeVersion": "14",
		  "program": "${workspaceFolder}/index.js"
		}
	],
}
```
If not you can close this issue.
